### ISSUE TITLE
Key recount without needing to do app restart

### ISSUE THREAD

**Issue by sqtcyrus** [SpeQtral/etsi-qkd-api#1]
Issue:
* start app
* request keys
* deplete key store; either to nothing or just down a bit
* Independent QKD app is running, producing new key files
* app does not update its internal state how many keys it thinks is available
* deplete key store to zero; only restart of app will refresh key counts

Suggested solution:
* In [kme.py](https://github.com/SpeQtral/etsi-qkd-api/blob/7079467f73630e34353cebee16c32665a7214085/api/kme.py#L67), extract out the code that does the "read and count keys from qcrypto files available at key_file_path" to a new and separate class method. Inside the __init__ method, call this new method.
* In the `get_status` method, also call this new method to refresh the key count from potentially new files

**Comment by ajrheng** [comment]
Added a ``crawler`` class for this purpose. It's crawler method ``get_stored_key_count`` is called when ``KME`` is instantiated, and when the API ``get_status`` method is called.
