### ISSUE TITLE
Byte Order

### ISSUE THREAD

**Issue by sqtcyrus** [SpeQtral/etsi-qkd-api#2]
Looking over [yonder](https://github.com/SpeQtral/etsi-qkd-api/blob/7079467f73630e34353cebee16c32665a7214085/api/helper.py#L296), and I am curious why you are using a big endian byte order here?

Most systems that we interact with use little endian while networking uses big endian.
Since the key is random gibberish anyway, as long as it's consistent, it should be fine.

**Comment by ajrheng** [comment]
I will admit the code was a copy paste from StackOverflow with little thought into the byte ordering. But the code is consistent with ordering and presents no issue under big endian, so this should not be a problem.
