### ISSUE TITLE
Building documentation issues

### ISSUE THREAD

**Issue by sqtcyrus** [SpeQtral/etsi-qkd-api#5]
I believe we need to add `sphinx-autodoc-typehints` in the [requirements.txt](https://github.com/SpeQtral/etsi-qkd-api/blob/7079467f73630e34353cebee16c32665a7214085/requirements.txt#L1) to be able to build the Sphnix documents. Maybe need `sphinx_rtd_theme` too.

I used:
```bash
$ make html
```

to generate the html tree.

I'm seeing a lot of:
```bash
.../etsi-qkd-api/api/helper.py:docstring of api.helper.bitstring_to_bytes:1: WARNING: duplicate object description of api.helper.bitstring_to_bytes, other instance in api, use :noindex: for one of them
.../etsi-qkd-api/api/helper.py:docstring of api.helper.concat_keys:1: WARNING: duplicate object description of api.helper.concat_keys, other instance in api, use :noindex: for one of them
```

I'm seeing a lot of "WARNING: duplicate object description". Is that to be expected?

**Comment by ajrheng** [comment]
I forgot to include the updated ``requirements.txt``--my bad. I have fixed it. However, one dependency, ``pycrypto <= 2.6.1``, which contains the cryptographic suites used in the chat_app, throws a Github Dependabot security warning. I think it has to do with this specific attack: [#253](https://github.com/pycrypto/pycrypto/issues/253). I'm not qualified enough to tell how serious this is, but I'm raising it for attention

On the Sphinx ``make html`` errors, I find that they do not affect the functionality of the documentation at all. I have tried to resolve them but it always seems to throw another problem, so for now I choose to leave them (I am not adept at using Sphinx skillfully at all..).

**Comment by sqtcyrus** [comment]
I just thought it was cool GitHub is doing vulnerability analysis 😮

I suggest looking into why it is considered insecure. Could be versioning. Could be you need to change to another python package. Either way, I'll leave it to you to investigate and recommend/implement a fix.

As for the warnings, meh.

As for the self deprecation, be nicer to yourself! You're doing great!

Cheers.

**Comment by sqtcyrus** [comment]
PS, see the comment I made about your Python package choice: https://github.com/SpeQtral/etsi-qkd-api/issues/7#issue-678759296

Please transition away from `pycrypto`.

**Comment by ajrheng** [comment]
I realized I had switched from ``pycrypto`` to ``pycryptodome`` (the replacement for ``pycrypto``) in another branch as I was aware of the vulnerabilities early. I just forgot to update ``requirements.txt`` in ``master``. Managing requirements in different branches can be confusing. Already fixed it!

**Comment by ajrheng** [comment]
I've included instructions on building the documentation locally on the README on GitHub, as well as instructions on updating the documentation hosted online. Hopefully that helps whoever is taking over this project!
