### ISSUE TITLE
Fix dead links in docs

### ISSUE THREAD

**Issue by sqtcyrus** [SpeQtral/etsi-qkd-api#8]
At [the apache page](https://speqtral.github.io/etsi-qkd-api/contents/apache.html) there are external references to apache/ngnix that are mistakenly pointing to local URI's.

Update the links to go to appropriate sites.

**Comment by sqtcyrus** [comment]
Also, it would be preferable to have copyable code instead of the picture: https://speqtral.github.io/etsi-qkd-api/_images/apacheconf.png

**Comment by sqtcyrus** [comment]
Lastly, link to a tutorial that you used to install your SSL certs, whether self-signed or created by [Let's Encrypt](https://letsencrypt.org/). There are many ways to accomplish this and many different types of certs, so knowing what method you followed will be helpful for future readers.

**Comment by sqtcyrus** [comment]
For Fedora, I needed:
```bash
# dnf install httpd python3-mod_wsgi.x86_64
```
For the certs, I followed: https://www.server-world.info/en/note?os=Fedora_31&p=ssl&f=1

For the config, I made:
```bash
# cat /etc/httpd/conf.d/etsi-qkd-api.conf 
<VirtualHost _default_:443>
	SSLEngine on
	SSLCertificateFile /etc/pki/tls/certs/server.crt
	SSLCertificateKeyFile /etc/pki/tls/certs/server.key

	ServerName 127.0.0.1

	WSGIDaemonProcess etsi-qkd-api python-path=/var/www:/home/cproctor/code/interns/etsi-qkd-api/venv/lib/python3.8/site-packages
	WSGIProcessGroup etsi-qkd-api

	WSGIScriptAlias / /home/cproctor/code/interns/etsi-qkd-api/app.wsgi
	<Directory /home/cproctor/code/interns/etsi-qkd-api>
		Options FollowSymlinks
		AllowOverride None
		Require all granted
	</Directory>
	Errorlog /var/log/httpd/error_log
	LogLevel warn
	CustomLog /var/log/httpd/access_log combined
</VirtualHost>
```

Good enough for doodling but something more comprehensive would be appreciated.

**Comment by ajrheng** [comment]
Fixed dead links and included a link to the Apache config file.

**Comment by ajrheng** [comment]
The SSL certs for this demo are certified using CM7. The steps are included in the section ``Running Senetas VM with API``.
